#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $NIR_REPO == "NIR BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $NIR_REPO == "NIR" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $NIR_REPO =~ $regex ]]
    then
        if [[ $NIR_REPO_BRANCH ]]
        then
            echo "${NIR_REPO}/archive/${NIR_REPO_BRANCH}.zip"
        else
            echo "${NIR_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="NIR.zip"
    echo "  ✨Downloading NIR BOT V3.0Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    NIRPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  LegendBot V3.0 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $LEGENDPATH
    echo "    • 🥀Starting NIR 🥀•    "
    echo "
    LEGENDBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
